# spec/spec_helper.rb

require 'simplecov'
SimpleCov.start do
  add_filter '.bundle/'
  add_filter 'UI.rb'
end

require 'ambulance'
require 'ambulance_repository'
require 'brigade'
require 'brigade_repository'
require 'city'
require 'digital_billboard'
require 'drone'
require 'drone_repository'
require 'gate_barrier'
require 'intersection'
require 'location'
require 'map'
require 'neighborhood'
require 'neighborhood_repository'
require 'notification'
require 'person'
require 'person_repository'
require 'police'
require 'police_repository'
require 'phone'
require 'pet'
require 'traffic_light'
require 'user'
require 'vehicle'
