require: 'rubocop-rspec'
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
AllCops:
  Exclude:
    - 'bin/*'
    - 'config/environments/*.rb'
    - 'config/initializers/*.rb'
    - 'config/application.rb'
    - 'config/spring.rb'
    - 'Gemfile'
    - 'Rakefile'
    - 'db/*.rb'
    - 'db/migrate/*.rb'
    - 'test/test_helper.rb'
    - 'spec/rails_helper.rb'